# Generated by Django 2.0.3 on 2022-04-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clsMan', '0001_initial'),
        ('courseMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EaxmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='考试类型')),
            ],
            options={
                'verbose_name': '考试类型',
                'verbose_name_plural': '考试类型',
            },
        ),
        migrations.CreateModel(
            name='ExamTable',
            fields=[
                ('examID', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('examName', models.CharField(max_length=100, verbose_name='考试名称')),
                ('examTime', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='考试时间')),
                ('examDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('classID', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='clsMan.ClassTable', verbose_name='考试班级')),
                ('courseID', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='courseMan.CourseTable', verbose_name='考试科目')),
                ('examType', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='examMan.EaxmType', verbose_name='考试类型')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
                'ordering': ['examID', 'examName'],
            },
        ),
    ]
