# Generated by Django 2.0.3 on 2022-04-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clsMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudTable',
            fields=[
                ('stuID', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='学号')),
                ('stuChName', models.CharField(max_length=100, verbose_name='中文名')),
                ('stuEnName', models.CharField(max_length=100, verbose_name='英文名')),
                ('stuRepublic', models.CharField(blank=True, max_length=100, null=True, verbose_name='国籍')),
                ('stuSex', models.CharField(blank=True, choices=[('男', 'male'), ('女', 'famale')], default='male', max_length=10, null=True, verbose_name='性别')),
                ('stuBirthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('stuDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='个人描述')),
                ('stuContact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('classID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clsMan.ClassTable', verbose_name='班级编号')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'ordering': ['stuID', 'stuEnName'],
            },
        ),
    ]
