# Generated by Django 2.0.3 on 2022-04-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stdMan', '0001_initial'),
        ('examMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudScoreTable',
            fields=[
                ('scoreID', models.AutoField(primary_key=True, serialize=False)),
                ('stuScore', models.CharField(default='', max_length=100, verbose_name='成绩')),
                ('examID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='examMan.ExamTable', verbose_name='考试ID')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdMan.StudTable', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
                'ordering': ['stud', 'stuScore'],
            },
        ),
    ]
