# Generated by Django 2.0.3 on 2022-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('techID', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.CharField(max_length=100, verbose_name='姓名')),
                ('techSex', models.CharField(blank=True, choices=[('男', '男'), ('男', '女')], default='男', max_length=10, null=True, verbose_name='性别')),
                ('techBirthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('techDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='个人描述')),
                ('techContact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'ordering': ['techID', 'techName'],
            },
        ),
    ]
