# Generated by Django 2.0.3 on 2022-04-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clsMan', '0001_initial'),
        ('teacherMan', '0001_initial'),
        ('stdMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '选课信息',
                'verbose_name_plural': '选课信息',
            },
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('courseID', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='课程ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='课程名称')),
                ('courseDesc', models.CharField(blank=True, max_length=100, verbose_name='课程描述')),
                ('classID', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='clsMan.ClassTable')),
                ('teacherID', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherMan.TeacherTable')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'ordering': ['courseID', 'courseName'],
            },
        ),
        migrations.AddField(
            model_name='choosecourse',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseMan.CourseTable', verbose_name='课程编号'),
        ),
        migrations.AddField(
            model_name='choosecourse',
            name='studID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdMan.StudTable', verbose_name='学号'),
        ),
    ]
